[package]
name = "picturer"
version = "0.1.0"
edition = "2021"

[dependencies]
image = { version = "0.25.5", default-features = false, features = ["png"] }
anyhow = "1.0.93"
flate2 = { version = "1.0.35", default-features = false, features = ["zlib"] }